# This is the Docker default root config file, which configures aratiny, the demo Knetminer instance
# used when no other option is given to Docker.
# 
# Your dataset will need its own version of this file. 
# 
 
"@includes":
- defaults-cfg.yml

# oxl: data/knowledge-network.oxl this is the default

# Details about the datset and supported species
# 
"dataset @merge":
  id: wheatknet-beta # TODO: must become poaceae, after fixing the proxy
  title: Poaceae Test Instance
  # organization: is in the defaults
  # sampleQueries: config/sample-queries.xml # this is a default
  # backgroundImage: config/background.jpg # this is the default 
  
  # ======> WARNING!
  # SemanticMotif.txt won't work if you include Arabidopsis (endless paths met).
  # For that to work, you need to use SemanticMotifs-no-ara.txt
  # I've also experienced problems with adding rice to the first two.
  #
  species:
  #- taxId: 3702
  #  scientificName: Arabidopsis Thaliana
  #  commonName: Thale cress
  #  # chromosomeBaseMap: config/species/base-map-3702.xml # this is the default
  - taxId: 4565
    scientificName: Triticum aestivum
    commonName: Bread Wheat
  - taxId: 4577
    scientificName: Zea mays
    commonName: Maize
  #- taxId: 39947
  #  scientificName: Oryza sativa Japonica Group
  #  commonName: Japonica rice    
