# This is the Docker default root config file, which configures aratiny, the demo Knetminer instance
# used when no other option is given to Docker.
# 
# Your dataset will need its own version of this file. 
# 
 
"@includes":
- defaults-cfg.yml

# oxl: data/knowledge-network.oxl this is the default

# Details about the datset and supported species
# 
"dataset @merge":
  id: wheatknet-beta # TODO: must become poaceae, after fixing the proxy
  title: Beta Poaceae KnetMiner
  version: 55 

  # Have a look here about YAML multi-line strings: http://yaml-multiline.info
  description: >-
    Beta version of the KnetMiner gene discovery platform for Arabidopsis, wheat and rice.
    The instance is auto-updated upon Knetminer rebuild (from GitHub Actions).  
  keywords: Knetminer Beta, Knetminer CI, wheat, rice, Arabidopsis
     
  # organization: is in the defaults
  # sampleQueries: config/sample-queries.xml # this is a default
  # backgroundImage: config/background.jpg # this is the default 
  
  # ======> WARNING!
  # SemanticMotif.txt won't work if you include Arabidopsis (endless paths met).
  # For that to work, you need to use SemanticMotifs-no-ara.txt
  # I've also experienced problems with adding rice to the first two.
  #
  species:
  - taxId: 3702
    scientificName: Arabidopsis thaliana
    commonName: Arabidopsis

  - taxId: 4565
    scientificName: Triticum aestivum
    commonName: Wheat

  - taxId: 39947
    scientificName: Oryza sativa Japonica
    commonName: Rice
    
#seedGenesFile: config/seed-genes-poaceae.tsv

# TODO: migrate to the new GA4 API BY July!!!
# WARNING: READ the notes in defaults-cfg.yml!
# 
googleAnalyticsAPI:
  # ===> READ notes in the default. API tracking WILL NOT WORK until these two are set
  measurementId: CONVERT UA-237399750-1 to GA4 property
  # ===> READ notes in the default. API tracking WILL NOT WORK until this is set
  apiSecret: SET-UP-ME

googleAnalyticsClient:
  # TODO: see above. THIS WILL STOP WORKING IN JULY
  # You need to convert it into a GA4 property (if not already done by Google) and
  # the set the measurement ID here
  measurementId: UA-237399750-1


# These are custom options, which aren't explicitly defined by the Knetminer configuration. 
# See KnetminerConfiguration.getCustomOptions() at https://tinyurl.com/2en342tb for details.
# 
# WARNING: DO NOT ABUSE this feature! As explained in the link above, this is an hack to help with provisional
# or uncommon configuration parameters. Using this section SHOULD BE AN EXCEPTION to defining configuration
# variables explicitly (out of this section), so that they can be validated. 
#
customOptions:
  ui:
    # Enable it to show a "give us feedback" banner on the UI. This is a feature used by us at knetminer.com
    # Likely, you don't want it enabled.
    betaFeedbackBannerEnabled: true
