# This is the Docker default root config file, which configures aratiny, the demo Knetminer instance
# used when no other option is given to Docker.
# 
# Your dataset will need its own version of this file. 
# 
 
"@includes":
- defaults-cfg.yml

oxl: data/knowledge-network.oxl 

# Details about the datset and supported species
# 
"dataset @merge":
  id: solanaceae
  title: Solanaceae Test Knetminer Instance
  description: Knetminer instance for Solanaceae species
  keywords: Tomato, Potato, Capsicum, Sweet Pepper

  version: 54
  creationDate: 20220915
  # These are in the defaults
  #organization: in the defaults 
  #provider:
  # sampleQueries: config/sample-queries.xml # this is a default
  # backgroundImage: config/background.jpg # this is the default 
  
  species:
     
  - taxId: 4113
    scientificName: Solanum tuberosum
    commonName: Potato
    
  - taxId: 4072
    scientificName: Capsicum annuum
    commonName: Capsicum
  
  - taxId: 4081
    scientificName: Solanum lycopersicum
    commonName: Tomato

# No spaces or lower case letters allowed in seed genes tsv
seedGenesFile: config/seed-genes-solanaceae.tsv
