"@includes":
- defaults-cfg.yml

# A config file that is used to show a standalone (not using Docker) Knetminer instance.
#
# This is automatic, since this config file is going to /tmp/aratiny-dataset/config
# oxl: /tmp/aratiny-dataset/data/knowledge-network.oxl

# Details about the datset and supported species
# 
"dataset @merge":
  id: aratiny
  title: Aratiny dataset
  version: 1.0-ex
  keywords: "Aratiny, Arabidopsis, Knetminer Test"
  description: >-
    A very small test dataset, based on subsampling the Poaceae dataset, and 
    used to build a test/reference Knetminer instance.

  # creationDate: default is the OXL'a last modified time  
  
  # organization: is in the defaults
  # sampleQueries: config/sample-queries.xml # this is a default
  # backgroundImage: config/background.jpg # this is the default 
  
  species:
  - taxId: 3702
    scientificName: Arabidopsis Thaliana
    commonName: Thale cress
    # chromosomeBaseMap: config/species/base-map-3702.xml # this is the default
  - taxId: 4565
    scientificName: Triticum aestivum
    commonName: Bread Wheat
  - taxId: 4577
    scientificName: Zea mays
    commonName: Maize
 