# This is the Docker default root config file, which configures aratiny, the demo Knetminer instance
# used when no other option is given to Docker.
# 
# Your dataset will need its own version of this file. 
# 
 
"@includes":
- defaults-cfg.yml

# oxl: data/knowledge-network.oxl this is the default

# Details about the datset and supported species
# 
"dataset @merge":
  id: cereals
  title: Cereals Premium Test
  description: >-
        Knetminer Cereals Premium resource includes genomes of Arabidopsis, wheat, rice janponica, rice indica, maize, barley and brachypodium. 
  keywords: wheat, rice, indica, Arabidopis, Maize, Barley, Brachypodium.
  version: 57
     
  # organization: is in the defaults
  # sampleQueries: config/sample-queries.xml # this is a default
  # backgroundImage: config/background.jpg # this is the default 
  
  # ======> WARNING!
  # SemanticMotif.txt won't work if you include Arabidopsis (endless paths met).
  # For that to work, you need to use SemanticMotifs-no-ara.txt
  # I've also experienced problems with adding rice to the first two.
  #
  species:

  - taxId: 3702
    scientificName: Arabidopsis thaliana
    commonName: Arabidopsis

  - taxId: 4565
    scientificName: Triticum aestivum
    commonName: Wheat

  - taxId: 4577
    scientificName: Zea mays
    commonName: Maize

  - taxId: 39946
    scientificName: Oryza sativa Indica
    commonName: Indian Rice

  - taxId: 39947
    scientificName: Oryza sativa Japonica
    commonName: Rice

  - taxId: 112509
    scientificName: Hordeum vulgare
    commonName: Barley

  - taxId: 15368
    scientificName: Brachypodium distachyon
    commonName: Brachypodium
   
    
#seedGenesFile: config/seed-genes-poaceae.tsv


# WARNING: READ the notes in defaults-cfg.yml!
# 
googleAnalyticsAPI:
  measurementId: G-31YFKXKSYH # Converted from old UA-237399750-1
  apiSecret: c9TGJqIBSVuKB1CoRcZ90Q

# We're using the same as the API, but we need to override defaults
googleAnalyticsClient:
  measurementId: G-31YFKXKSYH
  apiSecret: c9TGJqIBSVuKB1CoRcZ90Q


# These are custom options, which aren't explicitly defined by the Knetminer configuration. 
# See KnetminerConfiguration.getCustomOptions() at https://tinyurl.com/2en342tb for details.
# 
# WARNING: DO NOT ABUSE this feature! As explained in the link above, this is an hack to help with provisional
# or uncommon configuration parameters. Using this section SHOULD BE AN EXCEPTION to defining configuration
# variables explicitly (out of this section), so that they can be validated. 
#
customOptions:
  ui:
    # Enable it to show a "give us feedback" banner on the UI. This is a feature used by us at knetminer.com
    # Likely, you don't want it enabled.
    betaFeedbackBannerEnabled: false
