dataset_dir="$1"
myname=$(basename $0)

if [ "$dataset_dir" == '' ]; then
	cat <<EOT


	$myname <dataset volume path>
	
Deletes Docker-generated data and configuration files on a Docker volume (ie, local folder), so that the Knetminer
container can regenerate fresh versions of the new files.

For instance, $myname /home/wheat-dataset will clean-up the config/ and data/ subdirectories under the
targeted wheat-dataset/ directory. config/ is completely deleted, since its contents are completely generated by our Docker
container, data is left with the knowledge-network.oxl file, which is the only starting input the container needs to 
be provided from the outside.

EOT
	exit 1
fi 

# Some safety tests
for dir in "$dataset_dir" "$dataset_dir/config" "$dataset_dir/data"
do
	[ -d "$dir" ] && [ -r "$dir" ] && [ -w "$dir" ] && continue
	
	echo -e "\n\n\t'$dir' isn't accessible, I refuse to continue\n"
	exit 2
done

echo ''
echo -e "\tCleaning config"
cd "$dataset_dir"
cd config
rm -Rf *

echo -e "\tCleaning data"
cd ../data
rm -Rf *.tab index map*

echo -e "\tCleaning client-src"
cd ..
rm -Rf client-src

echo -e "\t"
echo -e "\n\tThe end\n"
