# A bare image, that prepares all the environment (OS, 3rd-party tools) to build/run Knetminer
#
# TODO: migrate to an official JDK8 image and stop using our own 
# (which was a re-tagged copy from somewhere in github). 
# 
FROM tomcat:9.0.36-jdk11-adoptopenjdk-hotspot

# TODO: Python is for AWS and that would be worth a separated image
# TODO: is python-dev needed?
# 
# TODO: the 'n' commands below downgrade Node.js, due to a lib clash problem
# (https://github.com/Rothamsted/knetminer/issues/432). This should be removed when
# that's fixed (in Travis too).
# 
# The /bin/sh link is rebuilt because its default points to dash (come on!) and we have
# scripts assuming bash instead.
#
RUN set -x \
  && apt-get update \
  && apt-get -y install maven git libxml2-utils npm \
  && apt-get -y install python python-pip \
	&& npm config set unsafe-perm true \
	&& npm install bower gulp -g \
  && npm install -g n \
  && n 11.15.0 \\
	&& echo '{"allow_root":true}' > /root/.bowerrc \
	&& pip install awscli \
	&& ln -fs /bin/bash /bin/sh
  
#CMD [ "echo", "DO NOT RUN ME, This is a base image, used to build the Knetminer runtime" ]
