# This is the Docker default root config file, which configures aratiny, the demo Knetminer instance
# used when no other option is given to Docker.
# 
# Your dataset will need its own version of this file. 
# 
 
"@includes":
- defaults-cfg.yml

# oxl: data/knowledge-network.oxl # this is the default 

# Details about the datset and supported species
# 
"dataset @merge":
  id: solanaceae
  title: Solanaceae Test Knetminer Instance
  description: Knetminer instance for Solanaceae species
  keywords: Tomato, Potato, Capsicum, Sweet Pepper, Asparagus, Beet, Cucumber, Carrot, Lettuce, Coyote Tobacco

  version: 58
  creationDate: 20240708
  # These are in the defaults
  #organization: in the defaults 
  #provider:
  # sampleQueries: config/sample-queries.xml # this is a default
  # backgroundImage: config/background.jpg # this is the default 
  
  species:
     
  - taxId: 3702
    scientificName: Arabidopsis thaliana
    commonName: Arabidopsis

  - taxId: 4113
    scientificName: Solanum tuberosum
    commonName: Potato
    
  - taxId: 4072
    scientificName: Capsicum annuum
    commonName: Pepper
  
  - taxId: 4081
    scientificName: Solanum lycopersicum
    commonName: Tomato
  
  - taxId: 4686
    scientificName: Asparagus officinalis
    commonName: Asparagus

  - taxId: 3555
    scientificName: Beta vulgaris
    commonName: Beet

  - taxId: 3659
    scientificName: Cucumis sativus
    commonName: Cucumber

  - taxId: 79200
    scientificName: Daucus carota
    commonName: Carrot

  - taxId: 4236
    scientificName: Lactuca sativa
    commonName: Lettuce

  - taxId: 49451
    scientificName: Nicotiana attenuata
    commonName: Coyote Tobacco

# No spaces or lower case letters allowed in seed genes tsv
# seedGenesFile: config/seed-genes-solanaceae.tsv
