# This is the Docker default root config file, which configures aratiny, the demo Knetminer instance
# used when no other option is given to Docker.
# 
# Your dataset will need its own version of this file. 
# 
 
"@includes":
- defaults-cfg.yml

oxl: data/knowledge-network.oxl 

# Details about the datset and supported species
# 
"dataset @merge":
  id: tropicana
  title: Tropical Plant Test Knetminer Instance
  description: Knetminer instance for Coffee and Banana species
  keywords: Coffee, Banana

  version: 54
  creationDate: 20220923
  # These are in the defaults
  #organization: in the defaults 
  #provider:
  # sampleQueries: config/sample-queries.xml # this is a default
  # backgroundImage: config/background.jpg # this is the default 
  
  species:
     
  - taxId: 214687
    scientificName: Musa acuminata
    commonName: Banana
    
  - taxId: 49390
    scientificName: Coffea canephora
    commonName: Coffee bean
  
# No spaces or lower case letters allowed in seed genes tsv
seedGenesFile: config/seed-genes-tropicana.tsv
