# A bare image, that prepares all the environment (OS, 3rd-party tools) to build/run Knetminer
#
# TODO: migrate to a more recent Tomcat version
# 
FROM tomcat:10-jdk17-temurin-jammy

# TODO: Python is for AWS and that would be worth a separated image
# TODO: is python-dev needed?
# 
# The /bin/sh link is rebuilt because its default points to dash (come on!) and we have
# scripts assuming bash instead.
#
# Note that Maven isn't used at runtime anymore, but we keep it nonetheless, because this image
# is also used by the CI scripts.
# 
RUN set -x \
	&& apt-get update \
	&& apt-get -y install maven git libxml2-utils \
	&& apt-get -y install python3 python3-pip \
	&& pip3 install awscli \
	&& ln -fs /bin/bash /bin/sh

ENTRYPOINT [ "/bin/sh", "-c" ] 
CMD [ "echo -e '\n\n\tDO NOT RUN ME, This is a base image, used to build the Knetminer runtime\n'" ]
