# This is the Docker default root config file, which configures aratiny, the demo Knetminer instance
# used when no other option is given to Docker.
# 
# Your dataset will need its own version of this file. 
# 
 
"@includes":
- defaults-cfg.yml

# oxl: data/knowledge-network.oxl this is the default

# Details about the datset and supported species
# 
"dataset @merge":
  id: ascomycota
  title: ascomycota Knetminer Instance
  description: Knetminer instance about ascomycota
  keywords: fusarium, f.graminearum, knetminer 
  version: 20220905
  creationDate: 20220905
  # These are in the defaults
  #organization: in the defaults 
  #provider:
  # sampleQueries: config/sample-queries.xml # this is a default
  # backgroundImage: config/background.jpg # this is the default 
  
  species:
  #- taxId: 3702
  #  scientificName: Arabidopsis Thaliana
  #  commonName: Thale cress
  #  # chromosomeBaseMap: config/species/base-map-3702.xml # this is the default
  - taxId: 1318462
    scientificName: Specie 1318462
    commonName: Specie 1318462
  - taxId: 227321
    scientificName: Specie 227321
    commonName: Specie 227321
  - taxId: 237561
    scientificName: Specie 237561
    commonName: Specie 237561
  - taxId: 242507
    scientificName: Specie 242507
    commonName: Specie 242507
  - taxId: 284812
    scientificName: Specie 284812
    commonName: Specie 284812
  - taxId: 330879
    scientificName: Specie 330879
    commonName: Specie 330879
  - taxId: 336722
    scientificName: Specie 336722
    commonName: Specie 336722
  - taxId: 367110
    scientificName: Specie 367110
    commonName: Specie 367110
  - taxId: 5518
    scientificName: Specie 5518
    commonName: Specie 5518
  - taxId: 559292
    scientificName: Specie 559292
    commonName: Specie 559292

seedGenesFile: config/seed-genes-example.tsv