# This is the Docker default root config file, which configures aratiny, the demo Knetminer instance
# used when no other option is given to Docker.
# 
# Your dataset will need its own version of this file. 
# 
 
"@includes":
- defaults-cfg.yml

# oxl: data/knowledge-network.oxl this is the default
oxl: data/knowledge-network-53.oxl # Currently, we're pointing to this.

# Details about the datset and supported species
# 
"dataset @merge":
  id: ascomycota
  title: ascomycota Knetminer Instance
  description: Knetminer instance about ascomycota
  keywords: fusarium, f.graminearum, knetminer 
  version: 54
  creationDate: 20220905
  # These are in the defaults
  #organization: in the defaults 
  #provider:
  # sampleQueries: config/sample-queries.xml # this is a default
  # backgroundImage: config/background.jpg # this is the default 
  
  species:
  
  #- taxId: 3702
  #  scientificName: Arabidopsis Thaliana
  #  commonName: Thale cress
  #  # chromosomeBaseMap: config/species/base-map-3702.xml # this is the default
    
  - taxId: 1318462
    scientificName: Fusarium culmorum CS7071
    commonName: Fusarium culmorum CS7071
    
  - taxId: 5518
    scientificName: Fusarium graminearum PH-1
    commonName: Fusarium graminearum
  
  - taxId: 336722
    scientificName: Zymoseptoria tritici
    commonName: Zymoseptoria tritici
  
  - taxId: 330879
    scientificName: Aspergillus fumigatus Af293
    commonName: Aspergillus fumigatus
  
  - taxId: 227321
    scientificName: Aspergillus nidulans
    commonName: Aspergillus nidulans
  
  - taxId: 237561
    scientificName: Candida albicans
    commonName: Candida albicans
  
  - taxId: 242507
    scientificName: Magnaporthe oryzae
    commonName: Magnaporthe oryzae
  
  - taxId: 367110
    scientificName: Neurospora crassa
    commonName: Neurospora crassa
  
  - taxId: 559292
    scientificName: Saccharomyces cerevisiae
    commonName: Saccharomyces cerevisiae
  
  - taxId: 284812
    scientificName: Schizosaccharomyces pombe
    commonName: Schizosaccharomyces pombe
  
#seedGenesFile: config/seed-genes-example.tsv
