# This is the Docker default root config file, which configures aratiny, the demo Knetminer instance
# used when no other option is given to Docker.
#
# Your dataset will need its own version of this file.
#
"@includes":
  - defaults-cfg.yml

# oxl: data/knowledge-network.oxl # this is the default

# Details about the datset and supported species
#
"dataset @merge":
  id: legumes-premium
  title: Legumes Premium Knetminer Instance
  description: Knetminer instance for Legumes species
  keywords: Peanut, Faba bean, French bean, Garden pea, Soybean, Thale-cress.

  version: 62
  creationDate: 20250918
  # These are in the defaults
  # organization: in the defaults
  # provider:
  # sampleQueries: config/sample-queries.xml # this is a default
  # backgroundImage: config/background.jpg # this is the default

species:

  - taxId: 3818
    scientificName: Arachis hypogaea
    commonName: Peanut

  - taxId: 3906
    scientificName: Vicia faba
    commonName: Faba bean

  - taxId: 3885
    scientificName: Phaseolus vulgaris
    commonName: French bean

  - taxId: 3888
    scientificName: Pisum sativum
    commonName: Garden pea

  - taxId: 3847
    scientificName: Glycine max
    commonName: Soybean
    
  - taxId: 3702
    scientificName: Arabidopsis thaliana
    commonName: Thale-cress

# No spaces or lower case letters allowed in seed genes tsv
# seedGenesFile: config/seed-genes-solanaceae.tsv